#!/bin/bash

# Tag Lines
#------------------------------------------------------------------------------

csrc(){ echo -n "Quit Save >lines |bc |uc {>Grep  } Find "; }
src(){ echo -n "Quit Save >lines |bcmt |ucmt {>Grep  } Find "; }
ptext(){ echo -n "Quit Save |fmt >words {>Grep  } Find "; }

# setup default tags line
export EDITTAGS="$(csrc)"

# Tool Functions
#------------------------------------------------------------------------------

# Regex search
Grep(){ grep -n "$@"; }

# Word and Line Counts
words(){ wc -w; }
lines(){ wc -l; }

# Block Comments for C and Scripting Languages
bc(){ sed -e 's/^/\/\//'; }
uc(){ sed -e 's/^\/\///'; }
bcmt(){ sed -e 's/^/#/'; }
ucmt(){ sed -e 's/^#//'; }

# Expand tabs to spaces
etabs(){ sed -e 's/\t/    /g'; }

# Add a line number to each line of the file
lnnum(){ nl -nln -ba; }

# Trim trailing whitspace
trim(){ sed -e 's/[\t ]\+$//'; }

# Hex editing functions
hex(){ xxd; }
nohex(){ xxd -r; }
