#!/bin/bash

# setup editor env
export PS1=":; "
export PATH="$HOME/.config/tide/tools:$HOME/bin:$PATH"
export EDITRCFILE="$HOME/.config/edit/editrc"
export BASH_ENV="$EDITRCFILE"
export PROMPT_COMMAND='tide_cd "$PWD"'

# Provide a cd function to change tide's working directory manually. This could
# be aliased or defined to cd but that interferes with some programs like rbenv.
function tide_cd(){ echo -en "\033P$PWD\a"; }
export -f tide_cd

edit(){
    [[ -f "$EDITRCFILE" ]] && . "$EDITRCFILE"

    # Now figure out the correct editor to execute
    if [[ -z "$DISPLAY" ]]; then
        "$EDITOR" "$@"
    else
        bkg tide "$@"
    fi
}
export -f edit

exec tide --
