#!/bin/sh
TAGFILE="$1"
TAG="$2"

if [ "" == "$TAG" ] || [ "" == "$TAGFILE" ]; then
    echo "Usage: $0 TAGFILE TAG"
    exit 1
fi

awk -v TAG="$TAG" '
BEGIN { FS = "[\t]+" }
($1 == TAG) {
    matchstr = $3
    sub(/^\//, "\"", matchstr)
    sub(/\/;"$/, "\"", matchstr)
    gsub(/\*/, "\\*", matchstr)
    print "grep -Hn", matchstr, $2, "| cut -d: -f1,2"
}
' "$TAGFILE" | /bin/sh | xpick
