.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "XEDIT" "1" "May 2017" "" ""
.
.SH "NAME"
\fBxedit\fR \- a text editor inspired by acme(1) from Plan 9 and Inferno
.
.SH "SYNOPSIS"
\fBxedit\fR [\fIfile\fR]
.
.SH "DESCRIPTION"
\fBxedit\fR is a text editor inspired by the Acme editor from the Plan 9 and Inferno operating systems\. Unlike Acme, \fBxedit\fR is a single window, single file editor\. Instead of baking a window manager into the editor, this job is relegated to an X11 window manager\. It is recommended that \fBxedit\fR be used with a tiling window manager such as dwm(1) or spectrwm(1)\. These window managers will make dealing with multiple windows much easier and more efficient\.
.
.SS "Windows"
\fBxedit\fR windows are divided into four basic regions: a one\-line status, an expanding tags region, a main content region and an adjacent scroll region\. The status region contains a set of symbolic flags indicating the current state of the editor followed by the path of the file being edited\. The tags region acts as scratch buffer for commands that can be executed to affect the file or the state of the editor\. As the content of this region grows it will expand up to a quarter of the size of the window shrinking the main coantent region in kind\. The main content region displays a view of the file currently being edited\. To the left of the content region is a narrow vertical region matching the height of the content region\. This region acts as a scrollbar for the content region\.
.
.SS "Scrolling"
The scroll bar is located to the left of the content region\. It\'s operation is similar to that of acme(1) or 9term(1)\. A left click on the scroll bar will scroll the adjacent line in the content region to the bottom of the window\. A right click will move the adjacent line in the content region to the top of the window\. A middle click will jump to an approximate location in the file determined by calculating the vertical distance from the top of the scrollbar and applying that as a percentage to the offset in the file\.
.
.SS "Typing and Editing"
Typed characters in \fBxedit\fR are delivered to the currently active region\. Which region is active is determined by the placement of the mouse or by keyboard shortcut\. That is to say, the focus follows the mouse much as it does in acme(1) but there is a keyboard shortcut that allows users to toggle focus between the content region and the tag region without using the mouse\.
.
.P
The mechanics of editing text in the tag and content region is identical with the exception of searching and saving\. Edited content in the tag region is not saved to disk unlike the content region\. This region is considered a scratch buffer for commands, notes, and other bits of text that are placed there temporarily\. The content region displays the current view of the file being edited and can be flushed to disk when requested\.
.
.P
Searching with a term selected in the tags region will search for the term in the content region rather than the tags region\. In this way a user can edit the search term incrementally and perform repeated searches through the content region\. Searching for a term in the content region \fIwill\fR search for the term in the content region however\.
.
.SH "TEXT SELECTION"
\fBxedit\fR uses a series of rules to determine how much text to select when the user executes a context sensitive selection, a search, or a context sensitive execution\. The following rules are applied in order until a match is found\.
.
.IP "1." 4
\fBCursor over \'(\' or \')\'\fR: Highlight text between the parentheses including nested parentheses\.
.
.IP "2." 4
\fBCursor over \'[\' or \']\'\fR: Highlight text between the brackets including nested brackets\.
.
.IP "3." 4
\fBCursor over \'{\' or \'}\'\fR: Highlight text between the braces including nested braces\.
.
.IP "4." 4
\fBCursor at beginning or end of line\fR: Highlight the entire line (including the newline)
.
.IP "5." 4
\fBCursor over alphanumeric character or underscore\fR: Highlight the word under the cursor consisting of only alphanumeric and underscore characters\.
.
.IP "" 0
.
.P
If none of the above rules match, \fBxedit\fR will simply highlight the block of non\-whitespace characters under the cursor\.
.
.SH "MOUSE HANDLING"
.
.TP
\fBLeft Button\fR
The left mouse button is used for selecting text or moving the cursor\. A single\-click will move the mose to the clicked location\. A double\-click will will select the object under the clicked location based on context as described in \fBTEXT SELECTION\fR\. A triple\-click will select the largest contiguous chunk of non\-whitespace characters at the clicked location\.
.
.TP
\fBMiddle Button\fR
The middle mouse button is used for executing text at the clicked location\. The command to be executed is determined by the context rules defined in the \fBTEXT SELECTION\fR section\. The cursor position is not changed on a middle click\.
.
.TP
\fBRight Button\fR
The right button is used to search for the next occurrence of the clicked text\. The search term is determined by the context rules defined in the \fBTEXT SELECTION\fR section\. The search direction follows the direction of the previous search operation\. The \fBShift\fR key can be held in combination with a click of the right mosue button in order to reverse the search direction\.
.
.SH "COMMAND EXECUTION"
\fBxedit\fR allows for the execution of any arbitrary text as a command\. The input and output to/from each command executed can be controlled by prepending one of a set of sigils defined below\. These sigils instruct \fBxedit\fR from where the command will receive its input and where it will place its output (both standard and errors)\.
.
.TP
\fB\'!\' \- Run command detached from editor\fR
The command will be executed in the background and all of its input and output file descriptors will be closed\.
.
.TP
\fB\'<\' \- Input from command\fR
The command will be executed in the background and its standard output will be placed in the content region\. Its error output will be placed in the tags region\.
.
.TP
\fB\'>\' \- Output to command\fR
The command will be executed in the background\. The currently selected text will be written to the command\'s standard input\. The command\'s standard output and standard error content will be written to the tags region\.
.
.TP
\fB\'|\' \- Pipe through command\fR
The command will be executed in the background\. The currently selected text will be written to the command\'s standard input\. The command\'s standard output will replace the currently selected text\. Any error output will be placed in the tags region\.
.
.TP
\fB\':\' \- Pipe through sed(1)\fR
Identical to \'|\' except that the command is always sed(1)\. This is a convenience shortcut to allow quick and easy access to sed for editing blocks of text\.
.
.TP
\fBCommands with no sigil\fR
Commands with none of the aforementioned sigils will be executed in the background and have their standard output placed in the content region and their error output placed in the tags region\.
.
.SH "KEYBOARD SHORTCUTS"
.
.SS "Unix Standard Shortcuts"
.
.TP
\fBCtrl+u\fR
Delete from the cursor position to the beginning of the line\.
.
.TP
\fBCtrl+k\fR
Delete from the cursor position to the end of the line\.
.
.TP
\fBCtrl+w\fR
Delete the word to the left\.
.
.TP
\fBCtrl+a\fR
Move cursor to the beginning of the line\.
.
.TP
\fBCtrl+e\fR
Move cursor to the end of the line\.
.
.SS "Cursor Movement and Selection"
The key combinations below are responsible for moving the cursor around the document by character, by word, or by line\. The \fBShift\fR modifier key can be applied to any of them to also extend the current selection to the new cursor position\.
.
.TP
\fBEscape\fR
Highlight the last contiguous block of inserted text or clear the current selection (deselect the currently selected text)\.
.
.TP
\fBLeft\fR
Move the cursor one character to the left\.
.
.TP
\fBRight\fR
Move the cursor one character to the right\.
.
.TP
\fBUp\fR
Move the cursor to theprevious line\.
.
.TP
\fBDown\fR
Move the cursor to the next line\.
.
.TP
\fBCtrl+Left\fR
Move the cursor to the beginning of the word to the left\.
.
.TP
\fBCtrl+Right\fR
Move the cursor to the end of the word to the right\.
.
.SS "Modern Text Editing Shortcuts"
.
.TP
\fBCtrl+s\fR
Save the contents of the content region to disk\.
.
.TP
\fBCtrl+z\fR
Undo the last change performed on the active region\.
.
.TP
\fBCtrl+y\fR
Redo the previously undone change on the active region\.
.
.TP
\fBCtrl+x\fR
Cut the selected text to the X11 CLIPBOARD selection\.
.
.TP
\fBCtrl+c\fR
Copy the selected text to the X11 CLIPBOARD selection\.
.
.TP
\fBCtrl+v\fR
Paste the contents of the X11 CLIPBOARD selection to the active region\.
.
.TP
\fBDelete\fR
Delete the character to the right\.
.
.TP
\fBCtrl+Delete\fR
Delete the word to the right\.
.
.TP
\fBBackspace\fR
Delete the character to the left\.
.
.TP
\fBCtrl+Backspace\fR
Delete the word to the left\.
.
.TP
\fBCtrl+Enter\fR
Create a new line after the current line and place the cursor there\.
.
.TP
\fBCtrl+Shift+Enter\fR
Create a new line before the current line and place the cursor there\.
.
.TP
\fBPageUp\fR
Scroll the active region up by one screenful of text\. The cursor is not affected by this operation\.
.
.TP
\fBPageDn\fR
Scroll the active region down by one screenful of text\. The cursor is not affected by this operation\.
.
.SS "Search Shortcuts"
The shortcuts below allow the user to search for selected text or by context\. The direction of the search defaults to the forward direction with regard to the position in the file\. Each search follows the direction of the previous search unless the \fBShift\fR modifier is applied\. The \fBShift\fR modifier causes the current search operation to be applied in the opposite direction of the previous\.
.
.TP
\fBCtrl+f\fR
Search for the next occurrence of the selected text in the content region\. If no text is currently selected, the text under the cursor is selected based on context as described in \fBTEXT SELECTION\fR\.
.
.TP
\fBCtrl+Alt+f\fR
Search for the next occurence previous search term in the content region\.
.
.SS "Implementation\-specific Shortcuts"
.
.TP
\fBCtrl+[\fR
Decrease the indent level of the selected text\.
.
.TP
\fBCtrl+]\fR
Increase the indent level of the selected text\.
.
.TP
\fBCtrl+h\fR
Highlight the item under cursor following the rules in \fBTEXT SELECTION\fR
.
.TP
\fBCtrl+t\fR
Toggle focus between the tags region and the content region\.
.
.TP
\fBCtrl+q\fR
Quit the editor\. If the file is modified a warning will be printed in the tags region and the editor will not quit\. Executing the shortcut twice within 250ms will ignore the warning and quit the editor without saving\.
.
.TP
\fBCtrl+d\fR
Execute the selected text as described in \fBCOMMAND EXECUTION\fR\. If no text is selected, the text under cursor is selecte dbased on context as described in \fBTEXT SELECTION\fR\.
.
.TP
\fBCtrl+o\fR
Launch xfilepick(1) to choose a file from a recursive list of files in the current deirectory and sub directories\. This file will be opened in a new instance of \fBxedit\fR\.
.
.TP
\fBCtrl+p\fR
Launch xtagpick(1) to select a tag from a ctags(1) generated index file\. \fBxedit\fR will jump to the selected ctag definition in the current window if the file is currently being edited\. Otherwise, a new instance of \fBxedit\fR will be launched with the target file and the cursor set to the line containing the definition\.
.
.TP
\fBCtrl+g\fR
Lookup the selected symbol or symbol under the cursor in a ctags(1) generated index file\. Jump to the location of the definition if it exist in the current file\. Otherwise, a new instance of \fBxedit\fR will be launched with the target file and the cursor set to the line containing the definition\.
.
.TP
\fBCtrl+n\fR
Open a new instance of \fBxedit\fR with no filename\.
.
.SH "BUILTINS"
.
.TP
\fBCut\fR
Cut the selection to the X11 CLIPBOARD selection\.
.
.TP
\fBCopy\fR
Copy the selection to the X11 CLIPBOARD selection\.
.
.TP
\fBEol\fR
Toggle the line\-ending style for the buffers contents between LF and CRLF
.
.TP
\fBFind [term]\fR
Find the next occurrence of the selected text\.
.
.TP
\fBGoTo [arg]\fR
Jump to a specific line number or symbol\.
.
.TP
\fBIndent\fR
Toggle the autoindent feature on or off\.
.
.TP
\fBPaste\fR
Paste the contents of the X11 CLIPBOARD selection into the buffer\.
.
.TP
\fBQuit\fR
Quit the editor\.
.
.TP
\fBRedo\fR
Redo the last undone change\.
.
.TP
\fBSave\fR
Save the contents of the buffer to disk\.
.
.TP
\fBSaveAs [path]\fR
Save the contents of the buffer to disk\. If a path argument is provided, the buffer will be saved to the new path\.
.
.TP
\fBTabs\fR
Toggle the expand tabs featuer on or off\.
.
.TP
\fBUndo\fR
Undo the previous edit\.
.
.SH "FILES"
.
.TP
\fB$HOME/\.config/edit/editrc\fR
Shell script loaded in current environment to make shell functions and environment variables available to xedit(1)
.
.SH "ENVIRONMENT"
.
.TP
\fBEDITTAGS\fR
The contents of this environment variable is used to initialize the contents of the tags region of the window\.
.
.TP
\fBSHELL\fR
The contents of this variable are used as the shell in which all non\-builtin commands are executed\. If this variable is not defined, sh(1) is used as a fallback shell\.
.
.SH "AUTHOR"
Michael D\. Lowis
.
.SH "SEE ALSO"
xedit(1) xpick(1) xfilepick(1) xtagpick(1)
