.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "XEDIT" "1" "March 2017" "" ""
.
.SH "NAME"
\fBxedit\fR \- a text editor inspired by Acme from Plan 9 and Inferno
.
.SH "SYNOPSIS"
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
.
.SH "FILES"
.
.SH "ENVIRONMENT"
.
.SH "DIAGNOSTICS"
.
.SH "BUGS"
.
.SH "AUTHOR"
.
.SH "SEE ALSO"

